[package]
name = "cgn-social"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web="4"
actix-files = "0.6"

env_logger = "0.9"
log = "0.4"

dotenv = "0.15.0"
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }